iWebServer/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from interface import views

urlpatterns = [
    path('auth/token', views.access_token, name='access_token'),
    path('auth/token/refresh', views.refresh_token, name='refresh_token'),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', login_required(views.dashboard), name='home'),
    path('base/', include('interface.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('myaccount.urls')),
)

#########################################################
urlpatterns += [
    path('web/api/', include('pcd.views.urls')),
]
#########################################################

interface/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from interface import views

urlpatterns = [
    path('', login_required(views.dashboard), name='dashboard'),
    path('forbidden', login_required(views.forbidden), name='forbidden'),
]

myaccount/urls.py
# from django.urls import re_path
# from . import views
#
# app_name = "myaccount"
# urlpatterns = [
#     re_path(r'^profile/$', views.profile, name='profile'),
#     re_path(r'^profile/update/$', views.profile_update, name='profile_update'),
# ]
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'myaccount'
urlpatterns = [
    path('profile/', login_required(views.profile), name='profile'),
    path('profile/update/', login_required(views.profile_update), name='profile_update'),
    path('profile/management/', login_required(views.management), name='management'),
    path('profile/management/user/add', login_required(views.new_user), name='new_user'),
    # url(r'^profile/management/user/(?P<pk>\d+)/delete$', login_required(views.delete_user), name='delete_user'),
    # url(r'^profile/management/user/(?P<pk>\d+)/type/set$', login_required(views.set_user_type), name='set_user_type'),
    # url(r'^profile/management/user/(?P<pk>\d+)/group/set$', login_required(views.set_user_group), name='set_user_group'),
    # path('profile/management/permissions/', login_required(views.management_groups), name='management_groups'),
    # url(r'profile/management/group/(?P<pk>\d+)/level/(?P<level>\d+)/details/$', login_required(views.group_perm_details), name='group_perm_details'),
]

myaccount/models.py
from django.db import models
from django.contrib.auth.models import User
from interface.models import ModelCommonInfo


class UserProfile(ModelCommonInfo):

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    org = models.CharField(
        'Organization', max_length=128, blank=True)

    telephone = models.CharField(
        'Telephone', max_length=50, blank=True)

    mod_date = models.DateTimeField('Last modified', auto_now=True)

    class Meta:
        verbose_name = 'User Profile'

    def __str__(self):
        return "{}'s profile".format(self.user.__str__())

myaccount/forms.py
from django import forms
from .models import UserProfile


class ProfileForm(forms.Form):

    first_name = forms.CharField(label='First Name', max_length=50, required=False)
    last_name = forms.CharField(label='Last Name', max_length=50, required=False)
    org = forms.CharField(label='Organization', max_length=50, required=False)
    telephone = forms.CharField(label='Telephone', max_length=50, required=False)


class SignupForm(forms.Form):

    def signup(self, request, user):
        user_profile = UserProfile()
        user_profile.user = user
        user.save()
        user_profile.save()

myaccount/views.py
from interface.utils.log_utils import loggerr
from django.contrib.auth.models import User, Group
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import UserProfile
from .forms import ProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

Log = loggerr(__name__).getLogger()


def profile(request):
    user = request.user
    return render(request, 'account/profile.html', {'user': user})


def profile_update(request):
    user = request.user
    user_profile = get_object_or_404(UserProfile, user=user)

    if request.method == "POST":
        form = ProfileForm(request.POST)

        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()

            user_profile.org = form.cleaned_data['org']
            user_profile.telephone = form.cleaned_data['telephone']
            user_profile.save()

            return HttpResponseRedirect(reverse('myaccount:profile'))
    else:
        default_data = {'first_name': user.first_name, 'last_name': user.last_name,
                        'org': user_profile.org, 'telephone': user_profile.telephone, }
        form = ProfileForm(default_data)

    return render(request, 'account/profile_update.html', {'form': form, 'user': user})

def management(request):
    if (not (request.user.has_perm('boards.all_access'))):
        return redirect('forbidden')
    users = User.objects.filter(is_superuser=False).exclude(username='AnonymousUser').order_by('-id')
    users_admin = []
    users_general = []
    users_guest = []

    for user in users:
        if (user.has_perm('boards.all_access')):
            user.UserType = 'Admin'
            users_admin.append(user)
        elif(user.has_perm('boards.regular_access')):
            user.UserType = 'Regular'
            users_general.append(user)
        else:
            user.UserType = 'Guest'
            users_guest.append(user)

    paginator = Paginator(users_admin + users_general + users_guest, 10)
    page = request.GET.get('page', 1)
    target_users = paginator.get_page(page)

    paras = {}
    paras['users'] = target_users
    # paras['groups'] = Group.objects.filter(name__in=[item.AreaName for item in UserControl.objects.filter(AreaName__isnull=False)])
    return render(request, 'management_userlist.html', paras)

def new_user(request):
    if (not (request.user.has_perm('boards.all_access'))):
        return redirect('forbidden')
    if (request.method == 'POST'):
        Log.d(request.POST)
        try:
            UserName = request.POST.get('UserName')
            Password = request.POST.get('Password')
            Email = request.POST.get('Email')
            if(UserName != None and UserName != '' and Password != None and Password != ''):
                User.objects.create_user(username=UserName, password=Password, email=Email)
                return redirect('myaccount:management')
        except Exception as err:
            Log.e('new_user err:[' + str(err) + ']')
    return HttpResponse('404 Error')

def delete_user(request, pk):
    if (not (request.user.has_perm('boards.all_access'))):
        return redirect('forbidden')
    user = get_object_or_404(User, pk=pk)
    if (user.is_superuser or user.has_perm('boards.all_access')):
        return HttpResponse('404 Error')
    groups = Group.objects.filter(name='RegularGroup')
    if (len(groups) == 1):
        group = groups[0]
        group.user_set.remove(user)
    user.delete()
    return redirect('myaccount:management')

def set_user_type(request, pk):
    if (not (request.user.has_perm('boards.all_access'))):
        return redirect('forbidden')
    if(request.method != 'POST'):
        return redirect('forbidden')
    user = get_object_or_404(User, pk=pk)
    if(user.is_superuser or user.has_perm('boards.all_access')):
        return HttpResponse('404 Error')

    UserType = request.POST.get('UserType')
    if(UserType == None):
        Log.d('UserType error')
        return HttpResponse('404 Error')

    if(UserType == 'Regular' and not user.has_perm('boards.regular_access')):
        groups = Group.objects.filter(name='RegularGroup')
        if(len(groups) == 1):
            group = groups[0]
            group.user_set.add(user)
            return redirect('myaccount:management')
    elif(UserType == 'Guest' and user.has_perm('boards.regular_access')):
        groups = Group.objects.filter(name='RegularGroup')
        if (len(groups) == 1):
            group = groups[0]
            group.user_set.remove(user)
            return redirect('myaccount:management')
    return HttpResponse('404 Error')

# def set_user_group(request, pk):
#     if (not (request.user.has_perm('boards.all_access'))):
#         return redirect('forbidden')
#     if(request.method != 'POST'):
#         return redirect('forbidden')
#     user = get_object_or_404(User, pk=pk)
#     if(user.is_superuser or user.has_perm('boards.all_access')):
#         return HttpResponse('404 Error')
#
#     GroupName = request.POST.get('GroupName')
#     if(GroupName == None):
#         Log.d('GroupName error')
#         return HttpResponse('404 Error')
#
#     groups = Group.objects.filter(name=GroupName)
#     if (groups.count() == 1):
#         group = groups[0]
#         user.groups.clear()
#         user.groups.add(group)
#         Log.d('set user {} group to {} succeed'.format(user.username, group.name))
#         return redirect('myaccount:management')
#
#     return HttpResagement_groups(request):
#     if (not (request.user.has_perm('boards.all_access'))):
#         return redirect('forbidden')
#     user_controls = UserControl.objects.filter().order_by('Level', '-id')
#     page = request.GET.get('page', 1)
#     target_user_controls = Paginator(user_controls, 10).get_page(page)
#     user_control_province = UserControl.objects.filter(Level=1).last()
#
#     paras = {}
#     paras['user_controls'] = target_user_controls
#     paras['user_control_province'] = user_control_province
#     return render(ponse('404 Error')

# def manrequest, 'management_grouplist.html', paras)

# def group_perm_details(request, pk, level):
#     if (not (request.user.has_perm('boards.all_access'))):
#         return redirect('forbidden')
#     util = UserControlUtils()
#     user_control = UserControl.objects.filter(pk=pk).last()
#     Level = int(level)
#     user_control_province = UserControl.objects.filter(Level=1).last()
#
#     if (request.method == 'POST'):
#         Name = CommonTools.GetPara(request, 'Name', user_control)
#         b_need_update = False
#
#         if(user_control == None and ((Name != None and Name != '') or (user_control_province != None and Level == 1))):
#             if(UserControl.objects.filter(Name=Name).last() != None):
#                 return redirect('myaccount:group_perm_details', pk, level)
#
#         user_control = UserControl() if (user_control == None) else user_control
#         if(Name != None and Name != ''):
#             b_need_update = True if(user_control.Name != Name) else b_need_update
#             user_control.Name = Name
#             user_control.Desc = user_control.Name
#             user_control.AreaName = user_control.Name
#         else:
#             Log.e('Name is None')
#             return redirect('myaccount:group_perm_details', pk, level)
#         user_control.Level = Level
#         b_need_update = True if (user_control.Level != Level) else b_need_update
#         user_control.super_control = user_control_province if (Level > 1) else user_control.super_control
#         if(b_need_update):
#             user_control.save()
#             if(user_control.is_vaild() and user_control.super_control != None and user_control.super_control.is_vaild() and user_control.Level == 2):
#                 if(AreaInfo.objects.filter(ProvinceName=user_control.super_control.AreaName, CityName=user_control.AreaName).count() == 0):
#                     Log.d('we will create city {}'.format(user_control.AreaName))
#                     AreaInfo.objects.create(ProvinceName=user_control.super_control.AreaName, CityName=user_control.AreaName)
#
#         permission_list = []
#         if (request.POST.get('PermissionName') != None):
#             permission_list = request.POST.getlist('PermissionName')
#             Log.d('get permission list from request is ' + str(permission_list))
#         else:
#             Log.d('WARNING:PermissionName not set')
#
#         group = Group.objects.filter(name=user_control.Name).last()
#         group = group if(group != None) else Group.objects.create(name=user_control.Name)
#         util.InitPermissionObject()
#         Log.d('permission_list is' + str(permission_list))
#         for perm in permission_list:
#             Log.d('we will add {} for group {}'.format(perm, group.name))
#             util.AssignPermissionToObject(perm, user_control.AreaName)
#         for perm in util.GetPermissions(Level):
#             if(util.CheckPermissionToObject(perm, user_control.AreaName) and perm not in permission_list):
#                 Log.d('we will remove {} for group {}'.format(perm, group.name))
#                 remove_perm(perm, group, user_control)
#         save_access_log(request, 'New Group : {}'.format(Name))
#         return redirect('myaccount:management_groups')
#
#     permissions_selected = []
#     if(user_control == None):
#         permissions_selected = util.GetPermissions(Level)
#     else:
#         group = Group.objects.filter(name=user_control.Name).last()
#         if(group != None):
#             permissions_selected = util.GetObjectPermissions(user_control.AreaName)
#             permissions_selected = permissions_selected if(permissions_selected != None) else []
#     paras = {}
#     paras['user_control'] = user_control
#     paras['Level'] = Level

myaccount/templates/management_base.html
{% extends 'dark/base.html' %}
{% load i18n %}

{% block management_tab_color_tab_color %}active{% endblock %}

{% block main-container %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">{% trans 'Management' %}</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">{% trans 'Home' %}</a></li>
                    {% block breadcrumb %}
                    <li class="breadcrumb-item active"><a href="{% url 'myaccount:management' %}">{% trans 'Management' %}</a></li>
                    {% endblock %}
                </ol>
            </div>
        </div>
    </div>
    {% if 'myaccount:management' in MENU_NEED_URL  %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <ul class="nav nav-tabs customtab" role="tablist">
                        <li class="nav-item"> <a class="nav-link" href="{% url 'myaccount:management' %}" {% block management_userlist_tab_color %}{% endblock %}>{% trans 'Users' %} </a></li>
                        <li class="nav-item"> <a class="nav-link" href="{% url 'myaccount:management_groups' %}" {% block management_groups_tab_color %}{% endblock %}>{% trans 'Groups' %} </a></li>
                    </ul>
                    {% block management_nav_content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

myaccount/templates/management_group_details.html
{% extends 'management_base.html' %}
{% load static %}
{% load i18n %}

{% block stylesheet %}
<link href="{% static '/assets/node_modules/bootstrap-switch/bootstrap-switch.min.css' %}" rel="stylesheet">
<link href="{% static 'dark/dist/css/pages/bootstrap-switch.css' %}" rel="stylesheet">
{% endblock %}

{% block script_content_body %}
<script src="{% static '/assets/node_modules/bootstrap-switch/bootstrap-switch.min.js' %}"></script>
<script type="text/javascript">
    function changeStatus(){
        if(document.getElementById("config_status").checked) {
            document.getElementById("config_status_switch").value = 'running';
        } else {
            document.getElementById("config_status_switch").value = 'stopped';
        }
    }

    function changeSelector(id, value, desc=null) {
        if(id == null) {
            return ;
        }
        if(value == null) {
            document.getElementById(id + '_selector').textContent = "{% trans 'Please Select' %}";
            document.getElementById(id).value = '';
            return ;
        }
        document.getElementById(id + '_selector').textContent = (desc == null) ? value :desc;
        document.getElementById(id).value = value;
    }

    $(".bt-switch input[type='checkbox'], .bt-switch input[type='radio']").bootstrapSwitch();
    var radioswitch = function() {
        var bt = function() {
            $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioState")
            }), $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck")
            }), $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck", !1)
            })
        };
        return {
            init: function() {
                bt()
            }
        }
    }();
    $(document).ready(function() {
        radioswitch.init();
    });
</script>
{% endblock %}

{% block management_groups_tab_color %}style="color:#fb9678"{% endblock %}

{% block management_nav_content %}
<div class="row m-t-10">
    <form class="custom-checkbox" action="{% if user_control %}{% url 'myaccount:group_perm_details' user_control.pk Level %}{% else %}{% url 'myaccount:group_perm_details' 0 Level %}{% endif %}" method="post">
        {% csrf_token %}
        <div class="col-lg-12">
            <div class="card bg-light">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 input-user_control">
                            <label class="m-t-10" style="width: 105px">{% trans 'Group Name' %}:</label>
                            <input type="text" class="form-control" placeholder="{% if user_control %}{{ user_control.Name }}{% else %}{% trans 'Group name cannot be empty' %}{% endif %}" name="Name" {% if user_control %}value="{{ user_control.Name }}" disabled{% endif %}>
                        </div>
                        <div class="col-lg-6 input-user_control">
                            <label class="m-t-10" style="width: 121px">{% trans 'Level' %}:</label>
                            <input type="text" class="form-control" value="{% if Level == 1 %}{% trans 'Provincial Level' %}{% elif Level == 2 %}{% trans 'City Level' %}{% endif %}" disabled>
                        </div>
                    </div>
                    <div class="row m-t-20">
                        <div class="col-lg-8 bt-switch">
                            <div class="row">
                                <div class="col-lg-2 m-t-10">
                                    <label style="width: 121px">{% trans 'Permissions' %}:</label>
                                </div>
                                <div class="col-lg-10">
                                    <select class="selectpicker" data-style="form-control btn-secondary" name="PermissionName" multiple style="text-align: center">
                                        {% for permission in permissions %}
                                            <option value="{{ permission }}" {% if permission in permissions_selected %}selected{% endif %}>{{ permission }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-10">
                        <button class="btn btn-success" type="submit" style="width:130px">{% trans 'Submit' %}</button>
                        <a href="{% url 'myaccount:management' %}" class="btn btn-success ml-auto" style="width:160px">{% trans 'Back To Group List' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

myaccount/templates/management_grouplist.html
{% extends 'management_base.html' %}
{% load i18n %}

{% block management_groups_tab_color %}style="color:#fb9678"{% endblock %}

{% block management_nav_content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div>
                        <a href="{% url 'myaccount:group_perm_details' 0 2 %}" class="btn btn-info">{% trans 'New City Group' %}</a>
                    </div>
                    {% if not user_control_province %}
                    <div class="m-l-20">
                        <a href="{% url 'myaccount:group_perm_details' 0 1 %}" class="btn btn-info">{% trans 'New Provincial Group' %}</a>
                    </div>
                    {% endif %}
                </div>
                <div class="row m-t-10">
                    <div class="table-responsive">
                        <table class="table table-hover color-table info-table">
                            <thead>
                                <tr>
                                    <th>{% trans 'Group Name' %}</th>
                                    <th>{% trans 'Level' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user_control in user_controls %}
                                <tr>
                                    <td><a href="{% url 'myaccount:group_perm_details' user_control.pk user_control.Level %}">{{ user_control.AreaName }}</a></td>
                                    <td>{% if user_control.Level == 1 %}{% trans 'Provincial Level' %}{% elif user_control.Level == 2 %}{% trans 'City Level' %}{% endif %}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-5 offset-md-5">
        {% if user_controls.has_previous %}
            <a href="?page=1" class="btn btn-secondary" role="button">&laquo;</a>
            <a href="?page={{ user_controls.previous_page_number }}" class="btn btn-secondary" role="button">&lt;</a>
        {%  else %}
            <a href="#" class="btn btn-secondary disabled" role="button">&laquo;</a>
            <a href="#" class="btn btn-secondary disabled" role="button">&lt;</a>
        {% endif %}

        <button type="button" class="btn btn-secondary">{{ user_controls.number }}&nbsp;&nbsp;/&nbsp;&nbsp;{{ user_controls.paginator.num_pages }}</button>

        {% if user_controls.has_next %}
            <a href="?page={{ user_controls.next_page_number }}" class="btn btn-secondary" role="button">&gt;</a>
            <a href="?page={{ user_controls.paginator.num_pages }}" class="btn btn-secondary" role="button">&raquo;</a>
        {%  else %}
            <a href="#" class="btn btn-secondary disabled" role="button">&gt;</a>
            <a href="#" class="btn btn-secondary disabled" role="button">&raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}

myaccount/templates/management_userlist.html
{% extends 'management_base.html' %}
{% load i18n %}

{% block management_userlist_tab_color %}style="color:#fb9678"{% endblock %}

{% block management_nav_content %}
<div class="row">
    <div class="ml-auto m-r-10">
        <li class="box-label" style="list-style-type:none"><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" class="btn btn-info">+ {% trans 'Add User' %}</a></li>
        <div id="myModal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">{% trans 'Add User' %}</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" action="{% url 'myaccount:new_user' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>{% trans 'User Name' %}:</label>
                                <input type="text" class="form-control" name="UserName">
                                <label>{% trans 'User Password' %}:</label>
                                <input type="text" class="form-control" name="Password">
                                <label>{% trans 'Email' %}:</label>
                                <input type="text" class="form-control" name="Email">
                            </div>
                            <button type="submit" class="btn btn-info waves-effect">{% trans 'Add' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover color-table info-table">
                        <thead>
                            <tr>
                                <th>{% trans 'User Name' %}</th>
                                <th>{% trans 'Email' %}</th>
                                <th>{% trans 'Group' %}</th>
                                <th>{% trans 'Actions' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td>{{ user.username }}</td>
                                <td>{{ user.email }}</td>
                                {% if user.UserType != 'Admin' %}
                                <td>
                                    <form action="{% url 'myaccount:set_user_group' user.pk %}" method="post">
                                        {% csrf_token %}
                                        <select class="selectpicker" data-style="form-control btn-secondary" name="GroupName" {% if user.groups.count == 0 %}multiple{% endif %} onchange="this.form.submit()" style="text-align:right">
                                            {% for group in groups %}
                                                <option value="{{ group.name }}" {% if group in user.groups.all %}selected{% endif %}>{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </form>
                                </td>
                                <td>
                                    <li class="box-label" style="list-style-type:none"><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal_{{ user.pk }}">{% trans 'Delete' %}</a></li>
                                    <div id="myModal_{{ user.pk }}" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_{{ user.pk }}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="myModalLabel_{{ user.pk }}">{%  trans "Are you sure?" %}</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                </div>
                                                <div class="modal-body">
                                                    <form class="form-horizontal" action="{% url 'myaccount:delete_user' user.pk %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-info waves-effect">{%  trans "Yes,delete it!" %}</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                {% else %}
                                <td>{{ user.group.first.Name }}</td>
                                <td></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-5 offset-md-5">
        {% if users.has_previous %}
            <a href="?page=1" class="btn btn-secondary" role="button">&laquo;</a>
            <a href="?page={{ users.previous_page_number }}" class="btn btn-secondary" role="button">&lt;</a>
        {%  else %}
            <a href="#" class="btn btn-secondary disabled" role="button">&laquo;</a>
            <a href="#" class="btn btn-secondary disabled" role="button">&lt;</a>
        {% endif %}

        <button type="button" class="btn btn-secondary">{{ users.number }}&nbsp;&nbsp;/&nbsp;&nbsp;{{ users.paginator.num_pages }}</button>

        {% if users.has_next %}
            <a href="?page={{ users.next_page_number }}" class="btn btn-secondary" role="button">&gt;</a>
            <a href="?page={{ users.paginator.num_pages }}" class="btn btn-secondary" role="button">&raquo;</a>
        {%  else %}
            <a href="#" class="btn btn-secondary disabled" role="button">&gt;</a>
            <a href="#" class="btn btn-secondary disabled" role="button">&raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}